### ISSUE TITLE
老哥，啥时候更新自编译的方法吗？

### ISSUE THREAD

**Issue by PHCSJC** [cx9208/bbrplus#1]
在路由器上用，更换内核太困难，老哥啥时候更新下自编译的方法呢？armbian系统，谢谢！

**Comment by PHCSJC** [comment]
我尝试编译报错了：
root@n1:~# cat Makefile 
obj-m:=tcp_bbrplus.o
root@n1:~# make -s -C /lib/modules/$(uname -r)/build M=`pwd` modules CC=`which gcc`
/root/tcp_bbrplus.c: In function ‘bbr_drain_to_target_cycling’:
/root/tcp_bbrplus.c:238:17: error: implicit declaration of function ‘tcp_stamp_us_delta’ [-Werror=implicit-function-declaration]
                 tcp_stamp_us_delta(tp->delivered_mstamp, bbr->cycle_mstamp);
                 ^~~~~~~~~~~~~~~~~~
/root/tcp_bbrplus.c:246:27: error: incompatible types when assigning to type ‘u64 {aka long long unsigned int}’ from type ‘struct skb_mstamp’
         bbr->cycle_mstamp = tp->delivered_mstamp;
                           ^
/root/tcp_bbrplus.c: In function ‘bbr_cwnd_event’:
/root/tcp_bbrplus.c:410:35: error: ‘struct tcp_sock’ has no member named ‘tcp_mstamp’; did you mean ‘rcv_tstamp’?
         bbr->ack_epoch_mstamp = tp->tcp_mstamp;

**Comment by cx9208** [comment]
前段时间出去玩了，这两天都更新好。
