### ISSUE TITLE
是否 merge 的适配难度讨论

### ISSUE THREAD

**Issue by nanqinlang** [cx9208/bbrplus#2]
先感谢 op 找出一个新玩具

因为有一段时间没追 kernel 了，我在意的是 dog250 mod 于更新版本下的适配问题，即这份源码的 patches 具体包括了哪些代码，以及能否用于更新的内核环境

我目前还没看源码，先想到了这个问题

op 你怎么看

**Comment by cx9208** [comment]
适配到更高版本内核吗？因为我是够用党所以具体的也没有详细看，等爱折腾的来弄了233

**Comment by nanqinlang** [comment]
@cx9208 
为什么用 linux 还要做够用党。。。

**Comment by cx9208** [comment]
因为对kernel编程不熟而且忙啊233，有余力再学了
